// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okgitqzkqdxpubbaorzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rZ2l0cXprcWR4cHViYmFvcnp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MjM4NjYsImV4cCI6MjA1Nzk5OTg2Nn0.H6vshGYsHyOHK_6FUqDtf3sxUMBIV8wvJH1TZJSMmEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);